version: '3'

services:
  web:
    build:
      context: .  # Context should be the current directory where Dockerfile is located
      dockerfile: Dockerfile  # Make sure this is the correct name of your Dockerfile
    container_name: hms
    volumes:
      - .:/hms  # Mount the current directory into the container
    ports:
      - "8000:8000"  # Expose port 8000 for Django development server
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
